#!/usr/bin/env python3
"""
Citation reference table — core engine of Introduction Review Skill.
Hard-coded, deterministic. Name-based indexing via [CITE:lastnameYEAR] placeholders.

Output: 5-column table (# | Author | Body Context | Reference | Status).
Multiple occurrences of the same paper → sub-rows with  arrows.
"""

import re
import sys
import os
import json
from collections import OrderedDict

PLACEHOLDER_RE = re.compile(r'\[CITE:([a-zA-Z0-9_\-]+)\]')

DISCLAIMER_EN = (
    'This table was generated by a hard-coded script (cite_table.py). '
    'No LLM involvement — all citations trace back to real placeholders '
    'in the source text.'
)
DISCLAIMER_ZH = (
    '此表由硬编码脚本 (cite_table.py) 生成，无 LLM 参与 — '
    '所有引用均可追溯至源文本中的真实占位符。'
)


def detect_language(text):
    """Return 'zh' if >5% of chars are CJK, else 'en'."""
    clean = [c for c in text if not c.isspace()]
    if not clean:
        return 'en'
    cjk = sum(1 for c in clean if '一' <= c <= '鿿' or '　' <= c <= '〿')
    return 'zh' if cjk / len(clean) > 0.05 else 'en'


def scan_order(text):
    """Return placeholders in order of first appearance."""
    seen = OrderedDict()
    for match in PLACEHOLDER_RE.finditer(text):
        key = match.group(1)
        if key not in seen:
            seen[key] = len(seen) + 1
    return seen


def extract_context(text, start, end, half=20):
    """Extract ~half chars before and after the citation, total ~40 chars."""
    before = text[:start].replace('\n', ' ')
    after = text[end:].replace('\n', ' ')

    pre = before[-half:] if len(before) > half else before
    post = after[:half] if len(after) > half else after

    if len(before) > half:
        pre = '...' + pre
    if len(after) > half:
        post = post + '...'

    return pre + '[CITE_PLACEHOLDER]' + post


def format_author(key):
    """Extract author name from cite key: 'smith2023' -> 'Smith'."""
    name = re.split(r'\d', key)[0]
    if name and name[0].islower():
        name = name[0].upper() + name[1:]
    return name


def format_reference(key, num, paper_info=None):
    """Format reference column: '[N] Author, ShortTitle, Year'"""
    author = format_author(key)
    year = ''
    digits = re.findall(r'\d+', key)
    if digits:
        year = digits[-1]  # last number group is usually the year

    if paper_info and key in paper_info:
        info = paper_info[key]
        title = info.get('title_short', info.get('title', ''))
        yr = info.get('year', year)
        # abbreviate title: first 3 words, max 15 chars
        words = title.split()
        short = ' '.join(words[:3])
        if len(short) > 20:
            short = short[:17] + '...'
        return f'[{num}] {author}, {short}, {yr}'

    # fallback: author + year from key
    return f'[{num}] {author}, {year}'


def main():
    # Read draft
    draft_file = None
    if len(sys.argv) > 1 and sys.argv[1] not in ('--help', '-h'):
        draft_file = sys.argv[1]
        with open(draft_file, 'r', encoding='utf-8') as f:
            text = f.read()
    else:
        text = sys.stdin.read()

    # Detect language
    lang = detect_language(text)
    zh = lang == 'zh'

    # Localized strings
    num_hdr = '序号' if zh else '#'
    author_hdr = '作者' if zh else 'Author'
    ctx_hdr = '正文引用(前后20字)' if zh else 'Body Context (40)'
    ref_hdr = '参考文献' if zh else 'Reference'
    status_hdr = '状态' if zh else 'Status'
    disclaimer = DISCLAIMER_ZH if zh else DISCLAIMER_EN

    # Load paper info if available
    paper_info = {}
    if draft_file:
        info_file = os.path.splitext(draft_file)[0] + '_info.json'
        if os.path.exists(info_file):
            with open(info_file, 'r', encoding='utf-8') as f:
                paper_info = json.load(f)

    # Scan and map
    placeholders = scan_order(text)
    mapping = {k: placeholders[k] for k in placeholders}
    ordered_keys = list(placeholders.keys())
    total = len(ordered_keys)

    # Build occurrences with context
    occurrences = []
    for match in PLACEHOLDER_RE.finditer(text):
        key = match.group(1)
        num = mapping[key]
        ctx = extract_context(text, match.start(), match.end())
        ctx = ctx.replace('[CITE_PLACEHOLDER]', f'[{num}]')
        ref = format_reference(key, num, paper_info)
        occurrences.append({
            'num': num,
            'key': key,
            'context': ctx,
            'reference': ref,
        })

    # Determine first/sub rows
    key_seen = {}
    for occ in occurrences:
        key = occ['key']
        if key not in key_seen:
            key_seen[key] = 1
            occ['row_type'] = 'first'
            occ['status'] = '✅'
        else:
            occ['row_type'] = 'sub'
            occ['status'] = '✅'

    # Column widths
    w_num = 6
    w_author = 10
    w_ctx = 42
    w_ref = 28
    w_status = 6
    total_width = w_num + w_author + w_ctx + w_ref + w_status + 4

    # Build output
    lines = ['']
    lines.append(disclaimer)
    lines.append('')
    lines.append(
        f'{num_hdr:<{w_num}} '
        f'{author_hdr:<{w_author}} '
        f'{ctx_hdr:<{w_ctx}} '
        f'{ref_hdr:<{w_ref}} '
        f'{status_hdr:<{w_status}}'
    )
    lines.append('-' * total_width)

    for occ in occurrences:
        num = occ['num']
        key = occ['key']
        author = format_author(key)

        if occ['row_type'] == 'first':
            lines.append(
                f'[{num}]{" "*(w_num-3)} '
                f'{author:<{w_author}} '
                f'{occ["context"]:<{w_ctx}} '
                f'{occ["reference"]:<{w_ref}} '
                f'{occ["status"]:<{w_status}}'
            )
        else:
            lines.append(
                f'     ↳{" "*(w_num-4)} '
                f'{"↳":<{w_author}} '
                f'{occ["context"]:<{w_ctx}} '
                f'{"↳":<{w_ref}} '
                f'{occ["status"]:<{w_status}}'
            )

    lines.append('-' * total_width)
    lines.append(f'{len(key_seen)} references total, {len(occurrences)} occurrences.')

    output = '\n'.join(lines)
    print(output)

    # Write to file for Read relay
    out_file = os.path.join(os.path.dirname(__file__), 'cite_output.txt')
    with open(out_file, 'w', encoding='utf-8') as f:
        f.write(output)


if __name__ == '__main__':
    main()
