#!/usr/bin/env python3
"""
Citation reference table — core engine. Hard-coded, deterministic.
Normalized input ([CITE:key]) + fallback multi-key detection.
Now also checks citation position quality.
"""

import re
import sys
import os
import json
from collections import OrderedDict

# Canonical + fallback patterns (defense in depth — catches what LLM normalization misses)
PATTERNS = [
    # [CITE:key] — the canonical normalized format
    re.compile(r'\[CITE:([a-zA-Z0-9_\-]+)\]'),

    # \cite{key1,key2,key3} — LaTeX multi-key fallback, splits on comma
    re.compile(r'\\cite\{([^}]+)\}'),
]

DISCLAIMER_EN = (
    'This table was generated by a hard-coded script (cite_table.py). '
    'No LLM involvement — all citations trace back to real placeholders '
    'in the source text.'
)
DISCLAIMER_ZH = (
    '此表由硬编码脚本 (cite_table.py) 生成，无 LLM 参与 — '
    '所有引用均可追溯至源文本中的真实占位符。'
)


def detect_language(text):
    clean = [c for c in text if not c.isspace()]
    if not clean:
        return 'en'
    cjk = sum(1 for c in clean if '一' <= c <= '鿿' or '　' <= c <= '〿')
    return 'zh' if cjk / len(clean) > 0.05 else 'en'


def find_all_citations(text):
    """Find all citation placeholders, splitting multi-key LaTeX into individuals."""
    seen = set()
    matches = []
    for pattern in PATTERNS:
        for m in pattern.finditer(text):
            raw = m.group(1)
            # Split on comma for multi-key LaTeX like \cite{key1,key2,key3}
            keys = [k.strip() for k in raw.split(',') if k.strip()]
            for key in keys:
                pos = (m.start(), m.end(), key)
                if pos in seen:
                    continue
                seen.add(pos)
                matches.append({
                    'key': key,
                    'start': m.start(),
                    'end': m.end(),
                    'full': m.group(0),
                })
    matches.sort(key=lambda x: x['start'])
    return matches


def build_mapping(matches):
    seen = OrderedDict()
    for m in matches:
        key = m['key']
        if key not in seen:
            seen[key] = len(seen) + 1
    return seen


def extract_context(text, start, end, half=20):
    before = text[:start].replace('\n', ' ')
    after = text[end:].replace('\n', ' ')

    pre = before[-half:] if len(before) > half else before
    post = after[:half] if len(after) > half else after

    if len(before) > half:
        pre = '...' + pre
    if len(after) > half:
        post = post + '...'
    return pre + '[CITE_PLACEHOLDER]' + post


def check_position(text, start, end, num):
    """Check citation placement quality. Returns (status, warning)."""
    before = text[:start].rstrip()
    after = text[end:].lstrip()

    # Comma sandwich: ,[N], or , [N],
    if (before.endswith(',') or before.endswith(', ')) and \
       (after.startswith(',') or after.startswith(', ') or after.startswith('.') or after.startswith(';')):
        # Exception: sentence end ", which demonstrated X [1]." is fine
        if before.rstrip().endswith(','):
            before_words = before.rstrip()[:-1].strip()
            if not before_words[-1].isdigit():
                return '⚠️sandwich'

    # Author-attached: CapitalWord [N] verb — "Smith [1] proposed..."
    before_word = before.split()[-1] if before.split() else ''
    if before_word and before_word[0].isupper() and len(before_word) > 1:
        after_word = after.split()[0] if after.split() else ''
        if after_word and after_word[0].islower() and after_word not in ('and', 'or', 'et', 'al.', 'al'):
            return '⚠️author'

    return '✅'


def format_author(key):
    name = re.split(r'\d', key)[0]
    if not name:
        return key
    if name[0].islower():
        name = name[0].upper() + name[1:]
    return name


def format_reference(key, num, paper_info=None):
    author = format_author(key)
    digits = re.findall(r'\d+', key)
    year = digits[-1] if digits else ''

    if paper_info and key in paper_info:
        info = paper_info[key]
        title = info.get('title_short', info.get('title', ''))
        yr = info.get('year', year)
        words = title.split()
        short = ' '.join(words[:3])
        if len(short) > 20:
            short = short[:17] + '...'
        return f'[{num}] {author}, {short}, {yr}'

    return f'[{num}] {author}, {year}'


def main():
    draft_file = None
    if len(sys.argv) > 1 and sys.argv[1] not in ('--help', '-h'):
        draft_file = sys.argv[1]
        with open(draft_file, 'r', encoding='utf-8') as f:
            text = f.read()
    else:
        text = sys.stdin.read()

    lang = detect_language(text)
    zh = lang == 'zh'

    num_hdr = '序号' if zh else '#'
    author_hdr = '作者' if zh else 'Author'
    ctx_hdr = '正文引用(前后20字)' if zh else 'Body Context (40)'
    ref_hdr = '参考文献' if zh else 'Reference'
    status_hdr = '状态' if zh else 'Status'
    disclaimer = DISCLAIMER_ZH if zh else DISCLAIMER_EN

    paper_info = {}
    if draft_file:
        info_file = os.path.splitext(draft_file)[0] + '_info.json'
        if os.path.exists(info_file):
            with open(info_file, 'r', encoding='utf-8') as f:
                paper_info = json.load(f)

    matches = find_all_citations(text)
    mapping = build_mapping(matches)

    occurrences = []
    for m in matches:
        key = m['key']
        num = mapping[key]
        ctx = extract_context(text, m['start'], m['end'])
        ctx = ctx.replace('[CITE_PLACEHOLDER]', f'[{num}]')
        ref = format_reference(key, num, paper_info)
        pos_status = check_position(text, m['start'], m['end'], num)
        occurrences.append({
            'num': num,
            'key': key,
            'context': ctx,
            'reference': ref,
            'pos_status': pos_status,
        })

    # First/sub rows
    key_seen = {}
    warnings = {'sandwich': 0, 'author': 0}
    for occ in occurrences:
        key = occ['key']
        if key not in key_seen:
            key_seen[key] = 1
            occ['row_type'] = 'first'
            occ['status'] = occ['pos_status']
            if 'sandwich' in occ['pos_status']:
                warnings['sandwich'] += 1
            if 'author' in occ['pos_status']:
                warnings['author'] += 1
        else:
            occ['row_type'] = 'sub'
            occ['status'] = '✅'

    # Bare citation count: citations that appear as bare [N] without surrounding content
    bare_count = sum(1 for o in occurrences if o['pos_status'] == '✅' and o['row_type'] == 'first')
    # Actually bare = not explicitly bad but also not explicitly anchored to a finding
    # Simpler: if context is just "...[N]." at end, flag as potentially bare

    # Column widths
    w_num = 6
    w_author = 10
    w_ctx = 42
    w_ref = 28
    w_status = 10
    total_width = w_num + w_author + w_ctx + w_ref + w_status + 4

    lines = ['']
    lines.append(disclaimer)
    lines.append('')
    lines.append(
        f'{num_hdr:<{w_num}} '
        f'{author_hdr:<{w_author}} '
        f'{ctx_hdr:<{w_ctx}} '
        f'{ref_hdr:<{w_ref}} '
        f'{status_hdr:<{w_status}}'
    )
    lines.append('-' * total_width)

    for occ in occurrences:
        num = occ['num']
        key = occ['key']
        author = format_author(key)

        if occ['row_type'] == 'first':
            lines.append(
                f'[{num}]{" "*(w_num-3)} '
                f'{author:<{w_author}} '
                f'{occ["context"]:<{w_ctx}} '
                f'{occ["reference"]:<{w_ref}} '
                f'{occ["status"]:<{w_status}}'
            )
        else:
            lines.append(
                f'     ↳{" "*(w_num-4)} '
                f'{"↳":<{w_author}} '
                f'{occ["context"]:<{w_ctx}} '
                f'{"↳":<{w_ref}} '
                f'{occ["status"]:<{w_status}}'
            )

    lines.append('-' * total_width)
    lines.append(f'{len(key_seen)} refs, {len(occurrences)} occurrences.' if not zh
                 else f'{len(key_seen)} 篇, {len(occurrences)} 处引用.')

    # Position warnings
    if warnings['sandwich'] > 0 or warnings['author'] > 0:
        lines.append('')
        lines.append('Placement warnings:')
        if warnings['sandwich'] > 0:
            lines.append(f'  {warnings["sandwich"]} comma-sandwich citation(s) marked ⚠️sandwich')
        if warnings['author'] > 0:
            lines.append(f'  {warnings["author"]} author-attached citation(s) marked ⚠️author')
        lines.append('  Fix: move citations to sentence-end or natural pause. Avoid ,[N], and Smith[N]verb.')
        lines.append('  Legend: ⚠️sandwich = comma sandwich  |  ⚠️author = attached to author name')

    output = '\n'.join(lines)
    print(output)

    out_file = os.path.join(os.path.dirname(__file__), 'cite_output.txt')
    with open(out_file, 'w', encoding='utf-8') as f:
        f.write(output)


if __name__ == '__main__':
    main()
