#!/usr/bin/env python3
"""
Citation reference table generator.
Scans [CITE:xxx] placeholders, assigns numbers by first-appearance order,
outputs a compact plain-text table (avoids Claude Code output collapse).

Usage:
    python cite_table.py <input_file>
"""

import re
import sys
from collections import OrderedDict

PLACEHOLDER_RE = re.compile(r'\[CITE:([a-zA-Z0-9_\-]+)\]')
DISCLAIMER = (
    'This table was generated by a hard-coded script (cite_table.py). '
    'No LLM involvement — all citations trace back to real placeholders '
    'in the source text.'
)


def scan_order(text):
    seen = OrderedDict()
    for match in PLACEHOLDER_RE.finditer(text):
        key = match.group(1)
        if key not in seen:
            seen[key] = len(seen) + 1
    return seen


def extract_context(text, start, end, max_len=50):
    before = text[:start]
    after = text[end:]

    sent_start = 0
    for sep in ['. ', '.\n', '! ', '?\n', '!\n', '?\n']:
        idx = before.rfind(sep)
        if idx > sent_start:
            sent_start = idx + len(sep)

    sent_end = len(text)
    for sep in ['. ', '.\n', '! ', '? ', '!\n', '?\n']:
        idx = after.find(sep)
        if idx != -1 and idx + end < sent_end:
            sent_end = idx + end + 1
            break

    sentence = text[sent_start:sent_end].replace('\n', ' ').strip()
    if len(sentence) > max_len:
        sentence = sentence[:max_len - 3] + '...'
    return sentence


def format_author(key):
    name = re.split(r'\d', key)[0]
    if name and name[0].islower():
        name = name[0].upper() + name[1:]
    return name


def main():
    if len(sys.argv) > 1:
        with open(sys.argv[1], 'r', encoding='utf-8') as f:
            text = f.read()
    else:
        text = sys.stdin.read()

    placeholders = scan_order(text)
    mapping = {k: placeholders[k] for k in placeholders}

    occurrences = []
    for match in PLACEHOLDER_RE.finditer(text):
        key = match.group(1)
        num = mapping[key]
        ctx = extract_context(text, match.start(), match.end())
        ctx = ctx.replace(f'[CITE:{key}]', f'[{num}]')
        occurrences.append({'num': num, 'key': key, 'context': ctx})

    key_first_seen = {}
    for occ in occurrences:
        key = occ['key']
        if key not in key_first_seen:
            key_first_seen[key] = True
            occ['status'] = 'OK'
        else:
            occ['status'] = 'Reuse'

    # Compact plain-text table
    print()
    print(DISCLAIMER)
    print()
    print(f'{"#":<4} {"Author":<14} {"Context (50 chars)":<52} {"Status":<10}')
    print('-' * 82)

    seen = set()
    for occ in occurrences:
        key = occ['key']
        if key in seen:
            continue
        seen.add(key)
        print(f'{occ["num"]:<4} {format_author(key):<14} {occ["context"]:<52} {occ["status"]:<10}')

    print('-' * 82)
    print(f'{len(seen)} references total.')


if __name__ == '__main__':
    main()
